### ISSUE TITLE
Playlists?

### ISSUE THREAD

**Issue by SolidEva** [SpongeBobSun/Prodigal-iOS#1]
I don't see a menu to access playlists from my music library. Is this a limitation of iOS, or something that has yet to be implemented?

**Comment by SpongeBobSun** [comment]
I haven't implemented this yet. Currently playlist will only show current playing queue. I'm going to combine iTunes library and local file together along with playlists in next release. 

But I don't have any ETA for that due to this is a side project after all. If you want to add this feature yourself a pull request is always welcome.

Thanks for the feedback.
